ALTER TABLE student_practice_forms
    ADD COLUMN form_kind ENUM ('INTERVIEW','OBSERVATION') NOT NULL DEFAULT 'INTERVIEW';

ALTER TABLE student_practice_forms
    MODIFY target_role ENUM ('INSTITUTION_DIRECTOR','INSTITUTIONAL_TUTOR','STUDENT_SELF') NOT NULL;
