const STUDENT_ROLES = ['ROLE_ESTUDIANTE'];
const PRACTICE_TUTOR_ROLES = ['ROLE_TUTOR_PRACTICAS'];
const PRACTICE_REVIEW_ROLES = ['ROLE_TUTOR_PRACTICAS', 'ROLE_DIRECTOR_PRACTICAS'];
const INSTITUTIONAL_TUTOR_ROLES = ['ROLE_TUTOR_INSTITUCIONAL'];
const INSTITUTION_DIRECTOR_ROLES = ['ROLE_DIRECTORA_INSTITUCION'];
const PRACTICE_MANAGEMENT_ROLES = ['ROLE_DIRECTOR_PRACTICAS', 'ROLE_ADMIN'];
const DOCUMENT_PREFILL_READONLY_FIELDS = [
  'courseName',
  'studentUsername', // agregado para que el nombre de usuario del estudiante también se muestre como dato consultable
  'studentFullName',
  'studentIdentification',
  'studentEmail',
  'studentPhone',
  'academicPeriod',
  'subjectDenomination',
  'educationalInstitutionName',
  'educationalInstitutionCode',
  'educationalInstitutionAddress',
  'educationalInstitutionPhone',
  'educationalInstitutionEmail',
  'teacherCount',
  'studentCount',
  'mission',
  'vision',
  'institutionalValues',
  'curricularOrganizationUnit',
  'integrativeKnowledgeProject',
  'practiceType',
  'generalObjective',
  'specificObjective1',
  'specificObjective2',
  'specificObjective3',
];
const DOCUMENT_PREFILL_HIDDEN_FIELDS = ['courseId', 'educationalInstitutionId'];

export const DOCUMENT_MODULES = [
  {
    id: 'activity-plans',
    title: 'L.2. Plan de Actividades',
    documentOrder: 2,
    pdfFilename: 'L.2. Plan de Actividades.pdf',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_PRACTICAS', 'ROLE_DIRECTOR_PRACTICAS', 'ROLE_ADMIN'],
    listPath: '/api/activity-plans/me/summary',
    listRoles: STUDENT_ROLES,
    altLists: [
      { label: 'Por revisar', path: '/api/activity-plans/review/summary', roles: PRACTICE_TUTOR_ROLES },
      { label: 'Enviados', path: '/api/activity-plans/submitted/summary', roles: PRACTICE_MANAGEMENT_ROLES },
    ],
    createPath: '/api/activity-plans',
    createRoles: STUDENT_ROLES,
    prefillFromEnrollment: true,
    defaultsPath: (enrollmentId) => enrollmentId
      ? `/api/activity-plans/defaults?enrollmentId=${enrollmentId}`
      : '/api/activity-plans/defaults',
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/activity-plans/${id}`,
    updateRoles: STUDENT_ROLES,
    getPath: (id) => `/api/activity-plans/${id}`,
    pdfPath: (id) => `/api/activity-plans/${id}/pdf`,
    submitPath: (id) => `/api/activity-plans/${id}/submit`,
    submitRoles: STUDENT_ROLES,
    reviewPath: (id) => `/api/activity-plans/${id}/review`,
    reviewRoles: PRACTICE_REVIEW_ROLES,
    sample: activityPlanSample(),
    reviewSample: {
      approved: null,
      generalInfoFeedback: null,
      presentationFeedback: null,
      objectivesFeedback: null,
      activitiesFeedback: null,
      scheduleFeedback: null,
      resourcesFeedback: null,
      approvalFeedback: null,
    },
  },
  {
    id: 'practice-reports',
    title: 'L.1. Informe de Actividades Cumplidas',
    documentOrder: 1,
    pdfFilename: 'L.1. Informe de Actividades Cumplidas.pdf',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_PRACTICAS', 'ROLE_DIRECTOR_PRACTICAS', 'ROLE_ADMIN'],
    listPath: '/api/practice-reports/me/summary',
    listRoles: STUDENT_ROLES,
    altLists: [
      { label: 'Por revisar', path: '/api/practice-reports/review/summary', roles: PRACTICE_TUTOR_ROLES },
      { label: 'Enviados', path: '/api/practice-reports/submitted/summary', roles: PRACTICE_MANAGEMENT_ROLES },
    ],
    createPath: '/api/practice-reports',
    createRoles: STUDENT_ROLES,
    prefillFromEnrollment: true,
    defaultsPath: (enrollmentId) => enrollmentId
      ? `/api/practice-reports/defaults?enrollmentId=${enrollmentId}`
      : '/api/practice-reports/defaults',
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/practice-reports/${id}`,
    updateRoles: STUDENT_ROLES,
    getPath: (id) => `/api/practice-reports/${id}`,
    pdfPath: (id) => `/api/practice-reports/${id}/pdf`,
    submitPath: (id) => `/api/practice-reports/${id}/submit`,
    submitRoles: STUDENT_ROLES,
    reviewPath: (id) => `/api/practice-reports/${id}/review`,
    reviewRoles: PRACTICE_REVIEW_ROLES,
    sample: practiceReportSample(),
    reviewSample: {
      approved: null,
      generalInfoFeedback: null,
      presentationFeedback: null,
      objectivesFeedback: null,
      methodologyFeedback: null,
      activitiesFeedback: null,
      conclusionsFeedback: null,
      recommendationsFeedback: null,
      approvalFeedback: null,
    },
  },
  {
    id: 'final-reports',
    title: 'L.3. Informe Tutor Institucional',
    documentOrder: 3,
    pdfFilename: 'L.3. Informe Tutor Institucional.pdf',
    roles: [
      'ROLE_ESTUDIANTE',
      'ROLE_TUTOR_PRACTICAS',
      'ROLE_TUTOR_INSTITUCIONAL',
      'ROLE_DIRECTOR_PRACTICAS',
      'ROLE_ADMIN',
    ],
    listPath: '/api/final-reports/me/summary',
    listRoles: STUDENT_ROLES,
    altLists: [
      { label: 'Revision del tutor', path: '/api/final-reports/practice-review/summary', roles: PRACTICE_TUTOR_ROLES },
      { label: 'Revision institucional', path: '/api/final-reports/institutional-review/summary', roles: INSTITUTIONAL_TUTOR_ROLES },
      { label: 'Enviados', path: '/api/final-reports/submitted/summary', roles: PRACTICE_MANAGEMENT_ROLES },
    ],
    createPath: '/api/final-reports',
    createRoles: STUDENT_ROLES,
    prefillFromEnrollment: true,
    defaultsPath: (enrollmentId) => enrollmentId
      ? `/api/final-reports/defaults?enrollmentId=${enrollmentId}`
      : '/api/final-reports/defaults',
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/final-reports/${id}`,
    updateRoles: STUDENT_ROLES,
    getPath: (id) => `/api/final-reports/${id}`,
    pdfPath: (id) => `/api/final-reports/${id}/pdf`,
    submitPath: (id) => `/api/final-reports/${id}/submit`,
    submitRoles: STUDENT_ROLES,
    reviewPath: (id, roles = []) => roles.includes('ROLE_DIRECTOR_PRACTICAS')
      ? `/api/final-reports/${id}/director-review`
      : `/api/final-reports/${id}/practice-review`,
    reviewRoles: PRACTICE_REVIEW_ROLES,
    extraActions: [
      {
        label: 'Revision institucional',
        roles: INSTITUTIONAL_TUTOR_ROLES,
        needsId: true,
        body: true,
        sample: {
          approved: null,
          generalInfoFeedback: null,
          antecedentsFeedback: null,
          objectiveFeedback: null,
          activitiesFeedback: null,
          conclusionsFeedback: null,
          recommendationsFeedback: null,
          approvalFeedback: null,
        },
        path: (id) => `/api/final-reports/${id}/institutional-review`,
      },
      {
        label: 'Guardar comentarios institucionales',
        roles: INSTITUTIONAL_TUTOR_ROLES,
        needsId: true,
        body: true,
        method: 'PATCH',
        sample: {
          conclusion1: 'Conclusion relacionada con el objetivo especifico 1.',
          conclusion2: 'Conclusion relacionada con el objetivo especifico 2.',
          conclusion3: 'Conclusion relacionada con el objetivo especifico 3.',
          recommendation1: 'Recomendacion relacionada con la conclusion 1.',
          recommendation2: 'Recomendacion relacionada con la conclusion 2.',
          recommendation3: 'Recomendacion relacionada con la conclusion 3.',
        },
        path: (id) => `/api/final-reports/${id}/institutional-section`,
      },
    ],
    sample: finalReportSample(),
    reviewSample: {
      approved: null,
      generalInfoFeedback: null,
      antecedentsFeedback: null,
      objectiveFeedback: null,
      activitiesFeedback: null,
      conclusionsFeedback: null,
      recommendationsFeedback: null,
      approvalFeedback: null,
    },
  },
  {
    id: 'activity-evaluations',
    title: 'L.4. Evaluación de Actividades.',
    documentOrder: 4,
    pdfFilename: 'L.4. Evaluación de Actividades..pdf',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_PRACTICAS'],
    listPath: '/api/activity-evaluations/me',
    listRoles: STUDENT_ROLES,
    altLists: [{ label: 'Mis evaluaciones', path: '/api/activity-evaluations/managed', roles: PRACTICE_TUTOR_ROLES }],
    createPath: '/api/activity-evaluations',
    createRoles: PRACTICE_TUTOR_ROLES,
    prefillFromEnrollment: true,
    prefillEnrollmentPath: '/api/enrollments/managed',
    defaultsPath: (enrollmentId) => `/api/activity-evaluations/defaults?enrollmentId=${enrollmentId}`,
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/activity-evaluations/${id}`,
    updateRoles: PRACTICE_TUTOR_ROLES,
    getPath: (id) => `/api/activity-evaluations/${id}`,
    pdfPath: (id) => `/api/activity-evaluations/${id}/pdf`,
    sample: {
      enrollmentId: '',
      courseId: '',
      courseName: '',
      educationalInstitutionId: '',
      educationalInstitutionName: '',
      educationalInstitutionCode: '',
      educationalInstitutionAddress: '',
      educationalInstitutionPhone: '',
      educationalInstitutionEmail: '',
      practiceType: '',
      studentFullName: '',
      studentIdentification: '',
      studentEmail: '',
      studentPhone: '',
      academicPeriod: '',
      developmentMode: '',
      aspects: [
        {
          aspectType: 'GENERAL',
          item: '',
          level: '',
        },
        {
          aspectType: 'ESPECIFICO',
          item: '',
          level: '',
        },
      ],
      hoursCompleted: '',
      activitiesCompletionPercentage: '',
      evaluationDate: '',
    },
  },
  {
    id: 'follow-up',
    title: 'L.5. Reporte de Seguimiento',
    documentOrder: 5,
    pdfFilename: 'L.5. Reporte de Seguimiento.pdf',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_PRACTICAS'],
    listPath: '/api/practice-follow-up-reports/me',
    listRoles: STUDENT_ROLES,
    altLists: [{ label: 'Mis seguimientos', path: '/api/practice-follow-up-reports/managed', roles: PRACTICE_TUTOR_ROLES }],
    createPath: '/api/practice-follow-up-reports',
    createRoles: PRACTICE_TUTOR_ROLES,
    prefillFromEnrollment: true,
    prefillEnrollmentPath: '/api/enrollments/managed',
    defaultsPath: (enrollmentId) => `/api/practice-follow-up-reports/defaults?enrollmentId=${enrollmentId}`,
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/practice-follow-up-reports/${id}`,
    updateRoles: PRACTICE_TUTOR_ROLES,
    getPath: (id) => `/api/practice-follow-up-reports/${id}`,
    pdfPath: (id) => `/api/practice-follow-up-reports/${id}/pdf`,
    sample: {
      enrollmentId: '',
      courseId: '',
      courseName: '',
      educationalInstitutionId: '',
      educationalInstitutionName: '',
      educationalInstitutionCode: '',
      educationalInstitutionAddress: '',
      educationalInstitutionPhone: '',
      educationalInstitutionEmail: '',
      practiceType: '',
      studentFullName: '',
      studentIdentification: '',
      studentEmail: '',
      studentPhone: '',
      academicPeriod: '',
      developmentMode: '',
      sessions: [
        {
          supervisionDate: '',
          startTime: '',
          endTime: '',
          supervisedActivities: '',
        },
      ],
      deliveryDate: '',
    },
  },
  {
    id: 'completed-records',
    title: 'L.6. Registro de Actividades Cumplidas',
    documentOrder: 6,
    pdfFilename: 'L.6. Registro de Actividades Cumplidas.pdf',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_PRACTICAS', 'ROLE_DIRECTOR_PRACTICAS', 'ROLE_ADMIN'],
    listPath: '/api/completed-activity-records/me/summary',
    listRoles: STUDENT_ROLES,
    altLists: [
      { label: 'Por revisar', path: '/api/completed-activity-records/review/summary', roles: PRACTICE_TUTOR_ROLES },
      { label: 'Enviados', path: '/api/completed-activity-records/submitted/summary', roles: PRACTICE_MANAGEMENT_ROLES },
    ],
    createPath: '/api/completed-activity-records',
    createRoles: STUDENT_ROLES,
    prefillFromEnrollment: true,
    defaultsPath: (enrollmentId) => enrollmentId
      ? `/api/completed-activity-records/defaults?enrollmentId=${enrollmentId}`
      : '/api/completed-activity-records/defaults',
    readOnlyFields: DOCUMENT_PREFILL_READONLY_FIELDS,
    hiddenFields: DOCUMENT_PREFILL_HIDDEN_FIELDS,
    updatePath: (id) => `/api/completed-activity-records/${id}`,
    updateRoles: STUDENT_ROLES,
    getPath: (id) => `/api/completed-activity-records/${id}`,
    pdfPath: (id) => `/api/completed-activity-records/${id}/pdf`,
    submitPath: (id) => `/api/completed-activity-records/${id}/submit`,
    submitRoles: STUDENT_ROLES,
    reviewPath: (id) => `/api/completed-activity-records/${id}/review`,
    reviewRoles: PRACTICE_REVIEW_ROLES,
    sample: {
      enrollmentId: '',
      courseId: '',
      courseName: '',
      educationalInstitutionId: '',
      educationalInstitutionName: '',
      educationalInstitutionCode: '',
      educationalInstitutionAddress: '',
      educationalInstitutionPhone: '',
      educationalInstitutionEmail: '',
      practiceType: '',
      studentFullName: '',
      studentIdentification: '',
      studentEmail: '',
      studentPhone: '',
      academicPeriod: '',
      developmentMode: '',
      entries: [
        {
          activityDate: '',
          startTime: '',
          endTime: '',
          developedActivities: '',
          evidenceLink: '',
        },
      ],
      deliveryDate: '',
    },
    reviewSample: {
      approved: null,
      generalInfoFeedback: null,
      activitiesFeedback: null,
      accreditationFeedback: null,
      entryFeedback: [
        {
          entryId: '',
          feedback: null,
          suggestions: null,
        },
      ],
    },
  },
].map((module) => ({ preserveInactiveRows: true, ...module }));

export const SCHEDULE_MODULES = [
  {
    id: 'schedules',
    title: 'Jornadas y asistencias',
    roles: ['ROLE_ESTUDIANTE', 'ROLE_TUTOR_INSTITUCIONAL', 'ROLE_DIRECTORA_INSTITUCION'],
    listPath: '/api/practice-schedules/me',
    listRoles: STUDENT_ROLES,
    altLists: [
      { label: 'Mis jornadas', path: '/api/practice-schedules/managed', roles: INSTITUTIONAL_TUTOR_ROLES },
      { label: 'Jornadas de mi institucion', path: '/api/practice-schedules/institution-review', roles: INSTITUTION_DIRECTOR_ROLES },
    ],
    createPath: '/api/practice-schedules',
    createRoles: INSTITUTIONAL_TUTOR_ROLES,
    updatePath: (id) => `/api/practice-schedules/${id}`,
    updateRoles: INSTITUTIONAL_TUTOR_ROLES,
    getPath: (id) => `/api/practice-schedules/${id}`,
    secondaryLabel: 'Asistencia',
    extraActions: [
      {
        label: 'Registrar asistencia',
        roles: INSTITUTIONAL_TUTOR_ROLES,
        needsId: true,
        body: true,
        method: 'POST',
        sample: attendanceSample(),
        path: (id) => `/api/practice-schedules/${id}/attendances`,
      },
      {
        label: 'Actualizar asistencia',
        roles: INSTITUTIONAL_TUTOR_ROLES,
        needsId: true,
        needsSecondaryId: true,
        body: true,
        method: 'PUT',
        sample: attendanceSample(),
        path: (id, attendanceId) => `/api/practice-schedules/${id}/attendances/${attendanceId}`,
      },
    ],
    sample: {
      enrollmentId: '',
      startDate: '2026-05-14',
      endDate: '2026-06-14',
      observations: 'Jornada programada.',
      periods: [
        {
          dayOfWeek: 'MONDAY',
          startTime: '08:00',
          endTime: '12:00',
          place: 'Aula 1',
          notes: 'Jornada guiada',
        },
      ],
    },
    reviewSample: attendanceSample(),
  },
];

function attendanceSample() {
  return {
    schedulePeriodId: '',
    attendanceDate: '2026-05-14',
    startTime: '08:00',
    endTime: '12:00',
    totalMinutes: null,
    status: 'PRESENT',
    observations: 'Asistencia registrada',
  };
}

function activityPlanSample() {
  return {
    enrollmentId: '',
    courseId: '',
    courseName: '',
    // Datos del estudiante y la institución incluidos para personalizar fácilmente el documento
    studentUsername: '',
    studentFullName: '',
    studentIdentification: '',
    studentEmail: '',
    studentPhone: '',
    academicPeriod: '',
    subjectDenomination: '',
    educationalInstitutionId: '',
    educationalInstitutionName: '',
    educationalInstitutionCode: '',
    educationalInstitutionAddress: '',
    educationalInstitutionPhone: '',
    educationalInstitutionEmail: '',
    teacherCount: '',
    studentCount: '',
    mission: '',
    vision: '',
    institutionalValues: '',
    presentation: '',
    generalObjective: '',
    specificObjective1: '',
    specificObjective2: '',
    specificObjective3: '',
    activityWeeks: [
      {
        weekNumber: 1,
        startDate: '',
        endDate: '',
        activities: '',
      },
    ],
    scheduleWeeks: [
      {
        weekNumber: 1,
        startDate: '',
        endDate: '',
        scheduledActivities: '',
      },
    ],
    legalResources: '',
    humanResources: '',
    technologicalResources: '',
    physicalResources: '',
  };
}

function practiceReportSample() {
  return {
    enrollmentId: '',
    courseId: '',
    courseName: '',
    // Datos del estudiante y la institución añadidos para poder personalizarlos en el cuerpo de la petición
    studentUsername: '',
    studentFullName: '',
    studentIdentification: '',
    studentEmail: '',
    studentPhone: '',
    academicPeriod: '',
    subjectDenomination: '',
    educationalInstitutionId: '',
    educationalInstitutionName: '',
    educationalInstitutionCode: '',
    educationalInstitutionAddress: '',
    educationalInstitutionPhone: '',
    educationalInstitutionEmail: '',
    teacherCount: '',
    studentCount: '',
    mission: '',
    vision: '',
    institutionalValues: '',
    curricularOrganizationUnit: '',
    integrativeKnowledgeProject: '',
    practiceType: '',
    presentation: '',
    generalObjective: '',
    specificObjective1: '',
    specificObjective2: '',
    specificObjective3: '',
    methodology: '',
    activityWeeks: [
      {
        weekNumber: 1,
        startDate: '',
        endDate: '',
        activities: '',
      },
    ],
    conclusion1: '',
    conclusion2: '',
    conclusion3: '',
    recommendation1: '',
    recommendation2: '',
    recommendation3: '',
  };
}

function finalReportSample() {
  return {
    enrollmentId: '',
    courseId: '',
    courseName: '',
    // Datos del estudiante y de la institución para informe final
    studentUsername: '',
    studentFullName: '',
    studentIdentification: '',
    studentEmail: '',
    studentPhone: '',
    academicPeriod: '',
    subjectDenomination: '',
    educationalInstitutionId: '',
    educationalInstitutionName: '',
    educationalInstitutionCode: '',
    educationalInstitutionAddress: '',
    educationalInstitutionPhone: '',
    educationalInstitutionEmail: '',
    teacherCount: '',
    studentCount: '',
    mission: '',
    vision: '',
    institutionalValues: '',
    curricularOrganizationUnit: '',
    integrativeKnowledgeProject: '',
    practiceType: '',
    antecedents: '',
    objective: '',
    activityWeeks: [
      {
        weekNumber: 1,
        startDate: '',
        endDate: '',
        activities: '',
      },
    ],
  };
}
